### ISSUE TITLE
Flexplate is "Mixing 2D and 3D objects"

### ISSUE THREAD

**Issue by dandancheeseandham** [dandancheeseandham/cheesecore#20]
The nice curve on the tab gets ignored when full rendered.
![Screenshot from 2020-02-04 14-06-32](https://user-images.githubusercontent.com/44091159/73751984-0bddc980-4758-11ea-9a6f-5d7aaa16cb67.png)

```
WARNING: Mixing 2D and 3D objects is not supported, in file ../bed.scad, line 135 
WARNING: Ignoring 2D child object for 3D operation, in file ../bed.scad, line 135 
```
![Screenshot from 2020-02-04 14-06-55](https://user-images.githubusercontent.com/44091159/73751973-06807f00-4758-11ea-9c9d-784462a62935.png)

I tried to fix it with linear extrude, but couldn't find a working approach.

**Comment by lostapathy** [comment]
Your error trace shows the error is in ../bed.scad - would be helpful to reproduce things like this if you specified what file you were running to actually trigger this.
